# Generated by Django 2.2.5 on 2019-09-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190925_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklog',
            old_name='member_name',
            new_name='member',
        ),
    ]
