# Generated by Django 2.2.5 on 2019-10-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'blank'), ('Work In Progress', 'WorkInProgress'), ('Would Not Be Done', 'WouldNotBeDone'), ('To Be Done', 'ToBeDone')], default='blank', max_length=20, null=True),
        ),
    ]
