# Generated by Django 2.2.5 on 2019-10-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_worklog_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='jira_ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
