# Generated by Django 2.2.5 on 2019-10-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_auto_20191014_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
