# Generated by Django 2.2.5 on 2019-10-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20191014_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='jira_ticket_number',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
