# Generated by Django 2.2.5 on 2019-10-14 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_auto_20191014_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('WorkInProgress', 'WorkInProgress'), ('WouldNotBeDone', 'WouldNotBeDone'), ('ToBeDone', 'ToBeDone')], default='ToBeDone', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
