# Generated by Django 2.2.5 on 2019-10-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_auto_20191014_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Work In Progress', 'Work In Progress'), ('Would Not Be Done', 'Would Not Be Done'), ('To Be Done', 'To Be Done')], default='Submitted', max_length=20),
        ),
    ]
